services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ventiendabackend-app
    image: ventiendabackend-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    environment:
      APP_NAME: "Ve mi Tienda"
      APP_ENV: "local"
      APP_URL: "http://localhost:9000"

      DB_CONNECTION: "mysql"
      DB_HOST: "host.docker.internal"  # 👈 Ahora dinámico
      DB_PORT: "3306"
      DB_DATABASE: "vemitienda_backend_docker"
      DB_USERNAME: "docker"
      DB_PASSWORD: "dockeruser"

      MAIL_MAILER: "smtp"
      MAIL_HOST: "smtp.hostinger.com"
      MAIL_PORT: "587"
      MAIL_USERNAME: "info@vemitienda.com"
      MAIL_PASSWORD: "Admintecnologia2@.."
      MAIL_ENCRYPTION: ""
      MAIL_FROM_ADDRESS: "info@vemitienda.com"

    extra_hosts:
      - "host.docker.internal:host-gateway"  # 👈 Esto hace que funcione en WSL2 y tome la ip de la pc anfitriona dinámicamente
    networks:
      - app-network
    command: php-fpm

networks:
  app-network:
    driver: bridge
