version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-image
    container_name: vemitienda-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - vemitienda

  db:
    image: mysql:8.0.19
    container_name: vemitienda-db
    command:
      - "--secure-file-priv=NULL"
      - "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: vemitienda
      MYSQL_ROOT_PASSWORD: Luis1984..
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ~BaseDatosVemitienda:/var/lib/mysql/
    networks:
      - vemitienda

  nginx:
    image: nginx:alpine
    container_name: vemitienda-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - vemitienda

networks:
  vemitienda:
    name: vemitienda
    driver: bridge
