version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ventiendabackend-app
    image: ventiendabackend-app
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./node_modules:/var/www/node_modules
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=nombre_de_tu_base
      - DB_USERNAME=tu_usuario
      - DB_PASSWORD=tu_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
