services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vemitiendabackend-app
    image: vemitiendabackend-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - "9000"  # 👈 Cambié ports -> expose porque solo es interno
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_URL: ${APP_URL}

      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}

    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    command: php-fpm

  nginx:
    image: nginx:latest
    container_name: vemitiendabackend-nginx
    ports:
      - "9010:80"  # 👈 Este expone el puerto para que puedas acceder desde Windows en localhost:9010
    volumes:
      - .:/var/www  # 👈 Necesita acceder al código fuente también
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 👈 Le vamos a pasar un nginx.conf especial
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
